version: '3'

services:
    backend:
        image: youngtify-backend:1.0.0
        ports:
            - "9090:9090"
        networks: 
            - backend
        links: 
            - "cache"
        depends_on:
            - cache
            - realtime
    realtime:
        image: youngtify-realtime:1.0.0
        ports:
            - "3000:3000"
        networks: 
            - backend
    cache:
        image: "redis:6.2.3-alpine"
        ports: 
            - "6379:6379"
networks:
    backend:
